version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb_wenance
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /Users/a309197/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
